### ISSUE TITLE
NuGet package is not available

### ISSUE THREAD

**Issue by anuraj** [antoinebidault/HtmlToAmpConverter#1]
I couldn't find the NuGet package for this. Can you publish it?

**Comment by antoinebidault** [comment]
Ok strange issue, the "HtmlToAmpConverter" name seems to be already taken in nuget.org. However it does not appear in the package list https://www.nuget.org/packages?q=HtmlToAmpConverter. I'm contacting the support.

**Comment by anuraj** [comment]
Is it an unlisted package?
![image](https://user-images.githubusercontent.com/276411/107855381-ec3baf80-6e47-11eb-9567-66dff2cee439.png)
If it is unlisted I don't think it will come in the search results and other users may not be able to install it.

**Comment by antoinebidault** [comment]
No, I've typed directly the package name in url and found it finally with
the following massage "the owner has unlisted this package

**Comment by anuraj** [comment]
No idea. You may have to check with support. There might be some solution.

**Comment by antoinebidault** [comment]
Ok the nuget support has responded. They gave me back the package ownership . The package is now in production.
